/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List all sessions for the current player.
         */
        get: operations["list_sessions_api_v1_sessions_get"];
        put?: never;
        /**
         * Create Session
         * @description Create a new game session.
         */
        post: operations["create_session_api_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description Get the full game state for a session.
         */
        get: operations["get_session_api_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Delete a game session.
         */
        delete: operations["delete_session_api_v1_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get State Summary
         * @description Get a lightweight summary of the current game state.
         */
        get: operations["get_state_summary_api_v1_sessions__session_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Inventory
         * @description Get the character's inventory for a session.
         */
        get: operations["get_inventory_api_v1_sessions__session_id__inventory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History
         * @description Get paginated conversation history for a session.
         */
        get: operations["get_history_api_v1_sessions__session_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdaptationRecord
         * @description Record of a story outline adaptation.
         */
        AdaptationRecord: {
            /**
             * Reason
             * @description Why the outline was adapted
             */
            reason: string;
            /**
             * Changes
             * @description What changed in the outline
             */
            changes: string;
            /**
             * Timestamp
             * Format: date-time
             * @description When the adaptation occurred
             */
            timestamp?: string;
        };
        /**
         * BeatFlexibility
         * @description How much a beat can change.
         * @enum {string}
         */
        BeatFlexibility: "fixed" | "flexible" | "optional";
        /**
         * BeatStatus
         * @description Lifecycle status of a story beat.
         * @enum {string}
         */
        BeatStatus: "planned" | "active" | "resolved" | "skipped" | "adapted";
        /**
         * BeatSummary
         * @description Lightweight story beat info for the state summary.
         */
        BeatSummary: {
            /**
             * Summary
             * @description Beat description
             */
            summary: string;
            /**
             * Location
             * @description Where this beat takes place
             */
            location: string;
            /**
             * Status
             * @description Beat lifecycle status
             */
            status: string;
        };
        /**
         * Character
         * @description A player character in the game.
         */
        Character: {
            /**
             * Id
             * Format: uuid
             * @description Unique character identifier
             */
            id?: string;
            /**
             * Name
             * @description Character display name
             */
            name: string;
            /**
             * Profession
             * @description Character class or profession
             */
            profession: string;
            /**
             * Background
             * @description Character backstory
             * @default
             */
            background: string;
            /**
             * Stats
             * @description Character stats (health, energy, money, etc.)
             */
            stats?: {
                [key: string]: number;
            };
            /**
             * Status Effects
             * @description Active status effects
             */
            status_effects?: components["schemas"]["StatusEffect"][];
            /**
             * Level
             * @description Character level
             * @default 1
             */
            level: number;
            /**
             * Experience
             * @description Experience points
             * @default 0
             */
            experience: number;
            /**
             * Location Id
             * @description Current location ID
             * @default start
             */
            location_id: string;
        };
        /**
         * CharacterCreate
         * @description Character creation parameters.
         */
        CharacterCreate: {
            /**
             * Name
             * @description Character name
             */
            name: string;
            /**
             * Profession
             * @description Character class or profession
             */
            profession: string;
            /**
             * Background
             * @description Character backstory
             * @default
             */
            background: string;
        };
        /**
         * CharacterSummary
         * @description Lightweight character info for the state summary.
         */
        CharacterSummary: {
            /**
             * Name
             * @description Character display name
             */
            name: string;
            /**
             * Profession
             * @description Character class or profession
             */
            profession: string;
            /**
             * Level
             * @description Character level
             */
            level: number;
            /**
             * Health
             * @description Current health
             */
            health: number;
            /**
             * Max Health
             * @description Maximum health
             */
            max_health: number;
        };
        /**
         * Conversation
         * @description Conversation history for a game session.
         */
        Conversation: {
            /**
             * History
             * @description Ordered list of messages
             */
            history?: components["schemas"]["Message"][];
            /**
             * Window Size
             * @description Messages to include in agent context
             * @default 20
             */
            window_size: number;
            /**
             * Summary
             * @description Summary of older conversation history
             * @default
             */
            summary: string;
        };
        /**
         * DeleteResponse
         * @description Response for delete operations.
         */
        DeleteResponse: {
            /**
             * Success
             * @description Whether the operation succeeded
             */
            success: boolean;
        };
        /**
         * GameState
         * @description The complete game state for a session.
         */
        GameState: {
            /** @description Session metadata */
            session?: components["schemas"]["Session"];
            /** @description Player character */
            character?: components["schemas"]["Character"];
            /** @description Character inventory */
            inventory?: components["schemas"]["Inventory"];
            /** @description World state */
            world?: components["schemas"]["World"];
            /** @description Story state */
            story?: components["schemas"]["StoryState"];
            /** @description Conversation history */
            conversation?: components["schemas"]["Conversation"];
            /**
             * Recent Events
             * @description Recent game events
             */
            recent_events?: {
                [key: string]: unknown;
            }[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryResponse
         * @description Response for GET /sessions/{session_id}/history.
         */
        HistoryResponse: {
            /**
             * Messages
             * @description Conversation messages
             */
            messages: components["schemas"]["Message"][];
            /**
             * Total
             * @description Total number of messages
             */
            total: number;
        };
        /**
         * Inventory
         * @description A character's inventory.
         */
        Inventory: {
            /**
             * Items
             * @description Items in inventory
             */
            items?: components["schemas"]["Item"][];
            /**
             * Equipment
             * @description Equipment slots mapped to item IDs
             */
            equipment?: {
                [key: string]: string | null;
            };
            /**
             * Capacity
             * @description Max inventory size, None for unlimited
             */
            capacity?: number | null;
        };
        /**
         * InventoryResponse
         * @description Response for GET /sessions/{session_id}/inventory.
         */
        InventoryResponse: {
            /**
             * Items
             * @description Items in inventory
             */
            items: components["schemas"]["Item"][];
            /**
             * Equipment
             * @description Equipment slots
             */
            equipment: {
                [key: string]: string | null;
            };
        };
        /**
         * Item
         * @description An item in the game.
         */
        Item: {
            /**
             * Id
             * Format: uuid
             * @description Unique item identifier
             */
            id?: string;
            /**
             * Name
             * @description Display name of the item
             */
            name: string;
            /**
             * Description
             * @description Flavor text for the item
             * @default
             */
            description: string;
            /** @description Category of the item */
            item_type: components["schemas"]["ItemType"];
            /**
             * Quantity
             * @description Stack count
             * @default 1
             */
            quantity: number;
            /**
             * Properties
             * @description Genre-specific item properties
             */
            properties?: {
                [key: string]: unknown;
            };
        };
        /**
         * ItemType
         * @description Types of items.
         * @enum {string}
         */
        ItemType: "weapon" | "armor" | "consumable" | "key" | "misc";
        /**
         * Location
         * @description A location in the game world.
         */
        Location: {
            /**
             * Id
             * @description Unique location identifier
             */
            id: string;
            /**
             * Name
             * @description Display name of the location
             */
            name: string;
            /**
             * Description
             * @description Location description text
             * @default
             */
            description: string;
            /**
             * Connections
             * @description IDs of connected locations
             */
            connections?: string[];
            /**
             * Npcs Present
             * @description IDs of NPCs at this location
             */
            npcs_present?: string[];
            /**
             * Items Present
             * @description IDs of items at this location
             */
            items_present?: string[];
            /**
             * Visited
             * @description Whether the player has visited
             * @default false
             */
            visited: boolean;
        };
        /**
         * LocationSummary
         * @description Lightweight location info for the state summary.
         */
        LocationSummary: {
            /**
             * Id
             * @description Location identifier
             */
            id: string;
            /**
             * Name
             * @description Display name
             */
            name: string;
            /**
             * Description
             * @description Location description
             */
            description: string;
            /**
             * Connections
             * @description Connected location IDs
             */
            connections: string[];
        };
        /**
         * Message
         * @description A message in the conversation history.
         */
        Message: {
            /** @description Who sent the message */
            role: components["schemas"]["MessageRole"];
            /**
             * Content
             * @description Message text
             */
            content: string;
            /**
             * Timestamp
             * Format: date-time
             * @description When the message was sent
             */
            timestamp?: string;
            /**
             * Metadata
             * @description Additional message metadata
             */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * MessageRole
         * @description Role of a conversation message sender.
         * @enum {string}
         */
        MessageRole: "player" | "agent" | "system";
        /**
         * Session
         * @description Session metadata.
         */
        Session: {
            /**
             * Session Id
             * Format: uuid
             * @description Unique session identifier
             */
            session_id?: string;
            /**
             * Player Id
             * Format: uuid
             * @description Player who owns this session
             */
            player_id?: string;
            /**
             * Created At
             * Format: date-time
             * @description When the session was created
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             * @description When the state was last modified
             */
            updated_at?: string;
            /**
             * Schema Version
             * @description State schema version
             * @default 1
             */
            schema_version: number;
            /**
             * @description Session status
             * @default active
             */
            status: components["schemas"]["SessionStatus"];
        };
        /**
         * SessionCreateRequest
         * @description Request body for creating a new game session.
         */
        SessionCreateRequest: {
            /**
             * Genre
             * @description Game genre (e.g. fantasy, sci-fi)
             */
            genre: string;
            /** @description Character creation data */
            character: components["schemas"]["CharacterCreate"];
        };
        /**
         * SessionCreateResponse
         * @description Response for session creation.
         */
        SessionCreateResponse: {
            /**
             * Session Id
             * Format: uuid
             * @description ID of the created session
             */
            session_id: string;
            /** @description Initial game state */
            game_state: components["schemas"]["GameState"];
        };
        /**
         * SessionDetailResponse
         * @description Response for getting session details.
         */
        SessionDetailResponse: {
            /** @description Full game state */
            game_state: components["schemas"]["GameState"];
        };
        /**
         * SessionListResponse
         * @description Response for listing sessions.
         */
        SessionListResponse: {
            /**
             * Sessions
             * @description List of session summaries
             */
            sessions: components["schemas"]["SessionSummary"][];
        };
        /**
         * SessionStatus
         * @description Status of a game session.
         * @enum {string}
         */
        SessionStatus: "active" | "paused" | "completed" | "abandoned";
        /**
         * SessionSummary
         * @description Summary of a game session for listing.
         */
        SessionSummary: {
            /**
             * Session Id
             * Format: uuid
             * @description Session ID
             */
            session_id: string;
            /**
             * Character Name
             * @description Character name
             */
            character_name: string;
            /**
             * Genre
             * @description Game genre
             * @default
             */
            genre: string;
            /**
             * Status
             * @description Session status
             */
            status: string;
            /**
             * Created At
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Updated At
             * @description Last update timestamp
             */
            updated_at: string;
        };
        /**
         * StateSummaryResponse
         * @description Response for GET /sessions/{session_id}/state.
         */
        StateSummaryResponse: {
            /** @description Character summary */
            character: components["schemas"]["CharacterSummary"];
            /** @description Current location summary */
            location: components["schemas"]["LocationSummary"];
            /** @description Active story beat summary */
            story_beat?: components["schemas"]["BeatSummary"] | null;
        };
        /**
         * StatusEffect
         * @description An active status effect on a character.
         */
        StatusEffect: {
            /**
             * Name
             * @description Name of the status effect
             */
            name: string;
            /** @description Category of the effect */
            effect_type: components["schemas"]["StatusEffectType"];
            /**
             * Description
             * @description What this effect does
             * @default
             */
            description: string;
            /**
             * Duration
             * @description Remaining turns, None if permanent
             */
            duration?: number | null;
            /**
             * Magnitude
             * @description Strength of the effect
             * @default 1
             */
            magnitude: number;
        };
        /**
         * StatusEffectType
         * @description Types of status effects.
         * @enum {string}
         */
        StatusEffectType: "buff" | "debuff" | "condition";
        /**
         * StoryBeat
         * @description A planned narrative moment in the story arc.
         */
        StoryBeat: {
            /**
             * Summary
             * @description What should happen at this point (1-2 sentences)
             */
            summary: string;
            /**
             * Location
             * @description Where this beat takes place
             * @default any
             */
            location: string;
            /**
             * Trigger Conditions
             * @description Conditions that activate this beat
             */
            trigger_conditions?: string[];
            /**
             * Key Elements
             * @description NPCs, items, or events that should be present
             */
            key_elements?: string[];
            /**
             * Player Objectives
             * @description What the player can/should do
             */
            player_objectives?: string[];
            /**
             * Possible Outcomes
             * @description Ways this beat might resolve
             */
            possible_outcomes?: string[];
            /**
             * @description How much this beat can change
             * @default flexible
             */
            flexibility: components["schemas"]["BeatFlexibility"];
            /**
             * @description Current lifecycle status
             * @default planned
             */
            status: components["schemas"]["BeatStatus"];
        };
        /**
         * StoryOutline
         * @description The story outline for a game session.
         */
        StoryOutline: {
            /**
             * Premise
             * @description 2-3 sentence summary of the overall story
             */
            premise: string;
            /**
             * Setting
             * @description World, tone, genre description
             */
            setting: string;
            /**
             * Beats
             * @description Ordered sequence of narrative beats
             */
            beats?: components["schemas"]["StoryBeat"][];
        };
        /**
         * StoryState
         * @description Full story state for a game session.
         */
        StoryState: {
            /** @description The story outline */
            outline?: components["schemas"]["StoryOutline"] | null;
            /**
             * Active Beat Index
             * @description Index of the current active beat
             * @default 0
             */
            active_beat_index: number;
            /**
             * Summary
             * @description Condensed history of resolved beats
             * @default
             */
            summary: string;
            /**
             * Adaptations
             * @description History of outline adaptations
             */
            adaptations?: components["schemas"]["AdaptationRecord"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * World
         * @description The game world state.
         */
        World: {
            /**
             * Locations
             * @description Map of location ID to location data
             */
            locations?: {
                [key: string]: components["schemas"]["Location"];
            };
            /**
             * Current Location Id
             * @description Player's current location ID
             * @default start
             */
            current_location_id: string;
            /**
             * Discovered Locations
             * @description Set of discovered location IDs
             */
            discovered_locations?: string[];
            /**
             * World Flags
             * @description Key-value flags for world state changes
             */
            world_flags?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_sessions_api_v1_sessions_get: {
        parameters: {
            query?: never;
            header?: {
                "x-player-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                "x-player-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-player-id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_v1_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-player-id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_summary_api_v1_sessions__session_id__state_get: {
        parameters: {
            query?: never;
            header?: {
                "x-player-id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_inventory_api_v1_sessions__session_id__inventory_get: {
        parameters: {
            query?: never;
            header?: {
                "x-player-id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_api_v1_sessions__session_id__history_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-player-id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
